### ISSUE TITLE
複数スペースを登録したとき、ウォッチが１件もないスペースが一番最初にあると処理が止まる

### ISSUE THREAD

**Issue by jawahiko** [ongaq/backlogWatch#16]
本拡張、いつも便利に使わせてもらっています！
そしてV2になり、より一層使いやすくなりました！ありがとうございます！

早速ですが、表題の件です。

スペースA（ウォッチ0件）
スペースB（ウォッチ1件）
スペースC（ウォッチ20件）
という状態で登録すると、Chrome拡張ボタンを押したときのリスト表示でスペース切り替えのプルダウンが表示されずに「現在ウォッチしてる課題がないか、オプションでスペースの情報の入力がありません」の表示になってしまいました。
スペースAにウォッチを1件登録すれば解決するのですが、可能であればプルダウンでスペースを選択できるようにして頂けると助かります。

また、同じIssueに記述してしまって恐れ入りますが・・・
スペースA（ウォッチ1件）
スペースB（ウォッチ0件）
スペースC（ウォッチ20件）
という状態にした場合、スペース選択プルダウンは表示されるのですが、スペースBを選択したとき「データの取得に失敗しました」の表示となり、リスト表示自体の高さが小さいため、スペース選択プルダウンでスペースCが選択出来ない状態となってしまいました。
これは大量のスペースを登録した場合にウォッチ数が1件の場合でも発生しました。
工夫で乗り切れるかとは思いますが、改善頂けると助かります。。

そしてもう1つ・・・
一度ウォッチ0件のスペースを選択して「データの取得に失敗しました」の表示があると、別のスペースを選択してもずっと残ってしまっておりました。ウォッチ20件のスペースを選択して、ウォッチ0件のスペースを選択する。を連続して繰り返すと、「データの取得に失敗しました」の表示が積み重なる挙動となっておりました。

よろしくお願いいたします。

**Comment by ongaq** [comment]
@jawahiko 
報告ありがとうございます！こちら修正しv2.0.2でChromeストアに申請しました。
反映されるまで今暫くお待ち下さいmm

**Comment by jawahiko** [comment]
@ongaq さま、ありがとうございます！！迅速にご対応頂き大変助かります！修正を確認致しました！！
（次回何かあればプルリクぐらいできるようにソース読み込んでみます。。。）
