### ISSUE TITLE
【要望】選択したスペースを記憶していて欲しい

### ISSUE THREAD

**Issue by jawahiko** [ongaq/backlogWatch#17]
連続恐れ入ります。。。

拡張ボタンを押すたびに、1番上のスペースが選択されてしまうのでいちいちスペース選択プルダウンで選択する必要があり2クリック増えてしまっており、、、。

または、オプション画面で登録したスペースがアルファベット順で自動ソートされるのではなく、登録した順番を保持していただけると助かります。（よく使うスペース順に並び替えておいて、スペース選択プルダウンもその通りに表示される）

ご検討のほど、よろしくお願い致します。

**Comment by ongaq** [comment]
@jawahiko 
提案ありがとうございます！v2.0.2で直前まで見ていたスペースを保持するように変更しました。
反映されるまで今暫くお待ち下さいmm

**Comment by jawahiko** [comment]
@ongaq さま、ありがとうございます！反映を確認しました！想像以上に使いやすくなりました・・・！より一層快適なBacklogライフを送れます。。ありがとうございました！
