### ISSUE TITLE
BacklogのSPA化への対応

### ISSUE THREAD

**Issue by elysion-halcyon** [ongaq/backlogWatch#5]
Backlogの各課題ページから、親子課題一覧やリンクで他の課題ページへ移る際、画面遷移しない仕様になった。

その経路で他課題に移った際、画面右下の(backlogWatchの)ウォッチ状況が移動前の課題のもののままとなっている。

**Comment by ongaq** [comment]
ありがとうございます。対応しましたのでChromeウェブストア公開までしばらくお待ち下さい。
Backlog使わなくなってしまったので言われなければ気付けませんでした。
nulab blogぐらいは追っておきます。
