### ISSUE TITLE
現在のドメインに対応できていないようです

### ISSUE THREAD

**Issue by tate-3dq** [ongaq/backlogWatch#9]
xxxxx.backlog.jp のドメインには対応していますが、現在最新のドメインは xxxxx.backlog.com には対応できていないようです。
恐らくここかと思いますが、検討をお願いいたします。
https://github.com/ongaq/backlogWatch/blob/master/manifest.json#L15-L16

**Comment by ongaq** [comment]
ご連絡ありがとうございます。
https://registerjp.backlog.com/trial/with-new-account/plan/11
確認してみましたがほんとですね。今はbacklog.comドメインで作られるんですね…
backlog.jpと両立させる対応を行いましたのでストアの反映をお待ち下さい。
